In [36]:
import numpy as np
Rewards = np.array([[-15,30,25]]).T
P_Up = np.array([[.75,.25,0],[.5,.5,0],[0,.75,.25]])
P_D  = np.array([[.25,.75,0],[0,.5,.5],[0,.25,.75]])
policy = np.array([0,0,1])

In [37]:
P_Up

array([[0.75, 0.25, 0.  ],
       [0.5 , 0.5 , 0.  ],
       [0.  , 0.75, 0.25]])

In [38]:
array_list = [P_Up,P_D]

In [41]:
def V(policy,array,rewards,gamma = .666666667):
    # built up the matrix
    I_pi_mat = np.identity((3))
    for j in range(3): # iterate over our rows -> the s values
        for i in range(3): # iterate over the columns -> the s' values
             I_pi_mat[j,i] -= gamma*array[policy[j]][j,i]
    
    # solve for V
    V_out = np.linalg.solve(I_pi_mat,rewards)
    return V_out,I_pi_mat

In [ ]:
def greedy(policy,array,V):
    
    # build up our action response matrices
    Q_S_A = np.zeros((4,81))
    for k in range(4):
        for j in range(81): # iterate over our rows -> the s values
            Q_S_A[k,j] = array[k][j,:]@V[:]
    
    # find the max values for each dimension
    pi_new = np.zeros((81,1)).astype(int)
    for i in range(81):
        max_loc = np.where(Q_S_A[:,i]==np.max(Q_S_A[:,i]))[0]
#         if len(max_loc>1):
#             pi_new[i] = random.choice(max_loc) # select a random entry from the possible choices of max
#         else:
        pi_new[i] = max_loc[0]
    
    return pi_new.flatten(),Q_S_A

In [42]:
V(policy,array_list,Rewards)

(array([[-18.        ],
        [ 36.        ],
        [ 62.00000004]]), array([[ 0.5       , -0.16666667,  0.        ],
        [-0.33333333,  0.66666667,  0.        ],
        [ 0.        , -0.16666667,  0.5       ]]))

In [43]:
import numpy as np
import math
import random

f = open('prob_a1.txt','r')
p_a1 = f.read().splitlines()
f = open('prob_a2.txt','r')
p_a2 = f.read().splitlines()
f = open('prob_a3.txt','r')
p_a3 = f.read().splitlines()
f = open('prob_a4.txt','r')
p_a4 = f.read().splitlines()
f = open('rewards.txt','r')
rewards = f.read().splitlines()
rewards = [int(i) for i in rewards]
rewards = np.array([rewards]).T

In [45]:
p_a1_array = np.zeros((81,81))
p_a2_array = np.zeros((81,81))
p_a3_array = np.zeros((81,81))
p_a4_array = np.zeros((81,81))

In [46]:
data_list = [p_a1,p_a2,p_a3,p_a4]
array_list = [p_a1_array,p_a2_array,p_a3_array,p_a4_array]

# rows are for s
# columns are for s'
for j in range(4):
    for i in range(len(data_list[j])):
        col = int(data_list[j][i].split(' ')[0]) # columns are the s' values
        row = int(data_list[j][i].split(' ')[2]) # rows are the s values
        prob = float(data_list[j][i].split(' ')[4]) # probability
        array_list[j][row-1,col-1] = prob

In [50]:
p_a1[:10],print(array_list[0][:12,:12])

[[1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.975 0.    0.    0.    0.    0.    0.    0.    0.    0.925]
 [0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.95  0.025]
 [0.    0.    0.025 0.    0.    0.    0.    0.    0.    0.    0.025 0.05 ]]


(['1  1  1',
  '2  2  1',
  '3  3  0.975',
  '12  3  0.925',
  '4  4  1',
  '5  5  1',
  '6  6  1',
  '7  7  1',
  '8  8  1',
  '9  9  1'],
 None)

In [51]:
### OTHER TEST ####

In [ ]:
pi_mat[2,2],1-gamma*array_list[policy[2]][2,2],gamma*array_list[policy[2]][2,2]

In [ ]:
policy,Q = greedy(policy,array_list,Velo)

In [ ]:
## GREEDY POLICY ## UNIT TESTS
x = array_list[0][2,:]@Velo[:],array_list[1][2,:]@Velo[:],array_list[2][2,:]@Velo[:],array_list[3][2,:]@Velo[:]